spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: PAssw0rd
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update